package com.example.demo.services;
import com.example.demo.dto.*;import com.example.demo.models.*;import com.example.demo.repository.*;import org.junit.jupiter.api.*;import org.mockito.*;import java.math.BigDecimal;import java.time.LocalDate;import java.util.*;import static org.junit.jupiter.api.Assertions.*;import static org.mockito.ArgumentMatchers.any;import static org.mockito.Mockito.*;
class VentaServiceLotesTest{
    VentaRepository ventas=mock(VentaRepository.class);ProductoRepository productos=mock(ProductoRepository.class);ClienteRepository clientes=mock(ClienteRepository.class);LoteProductoRepository lotes=mock(LoteProductoRepository.class);VentaService service;
    @BeforeEach void setUp(){service=new VentaService(ventas,productos,clientes,null,null,null,null,lotes);when(ventas.save(any())).thenAnswer(i->{Venta v=i.getArgument(0);v.setId(1L);return v;});}
    @Test void consumeLotesPorVencimientoFefo(){Producto p=Producto.builder().id(2L).nombre("Yogur").stock(20).costo(new BigDecimal("500")).precioVenta(new BigDecimal("800")).unidadVenta(Producto.UnidadVenta.UNIDAD).build();LoteProducto primero=lote(p,5,LocalDate.now().plusDays(5));LoteProducto segundo=lote(p,5,LocalDate.now().plusDays(20));when(productos.findByIdForUpdate(2L)).thenReturn(Optional.of(p));when(lotes.cantidadTrazada(2L)).thenReturn(10L);when(lotes.cantidadVendible(2L)).thenReturn(10L);when(lotes.disponiblesFefo(2L)).thenReturn(List.of(primero,segundo));Venta result=service.crear(new VentaCreateDTO(null,List.of(new ItemVentaCreateDTO(2L,7))));assertEquals(0,primero.getCantidadDisponible());assertEquals(3,segundo.getCantidadDisponible());assertEquals(2,result.getItems().getFirst().getLotes().size());}
    @Test void noVendeStockVencido(){Producto p=Producto.builder().id(2L).nombre("Yogur").stock(5).costo(BigDecimal.ONE).precioVenta(BigDecimal.TEN).unidadVenta(Producto.UnidadVenta.UNIDAD).build();when(productos.findByIdForUpdate(2L)).thenReturn(Optional.of(p));when(lotes.cantidadTrazada(2L)).thenReturn(5L);when(lotes.cantidadVendible(2L)).thenReturn(0L);assertThrows(IllegalStateException.class,()->service.crear(new VentaCreateDTO(null,List.of(new ItemVentaCreateDTO(2L,1)))));verify(ventas,never()).save(any());}
    private LoteProducto lote(Producto p,int cantidad,LocalDate vencimiento){return LoteProducto.builder().producto(p).cantidadInicial(cantidad).cantidadDisponible(cantidad).fechaIngreso(LocalDate.now()).fechaVencimiento(vencimiento).costoUnitario(p.getCosto()).activo(true).build();}
}
