package com.example.demo.ui;
import com.example.demo.dto.*;import com.example.demo.services.*;
import com.vaadin.flow.component.button.*;import com.vaadin.flow.component.combobox.ComboBox;import com.vaadin.flow.component.dialog.Dialog;import com.vaadin.flow.component.grid.Grid;import com.vaadin.flow.component.orderedlayout.*;import com.vaadin.flow.component.textfield.*;import com.vaadin.flow.router.*;
@Route(value="inventario",layout=MainLayout.class) @PageTitle("Inventario | Franco")
public class InventarioView extends VerticalLayout{
    private final InventarioService service;private final ProductoService productos;private final Grid<MovimientoStockDTO> grid=new Grid<>(MovimientoStockDTO.class,false);
    public InventarioView(InventarioService service,ProductoService productos){this.service=service;this.productos=productos;addClassName("content-view");setSizeFull();Button adjust=new Button("Ajustar stock",e->form());adjust.addThemeVariants(ButtonVariant.LUMO_PRIMARY);
        grid.addColumn(MovimientoStockDTO::fecha).setHeader("Fecha");grid.addColumn(MovimientoStockDTO::producto).setHeader("Producto");grid.addColumn(MovimientoStockDTO::tipo).setHeader("Tipo");grid.addColumn(MovimientoStockDTO::cantidad).setHeader("Variación");grid.addColumn(m->m.stockAnterior()+" → "+m.stockNuevo()).setHeader("Stock");grid.addColumn(MovimientoStockDTO::descripcion).setHeader("Motivo");grid.addColumn(MovimientoStockDTO::usuario).setHeader("Usuario");add(ViewSupport.header("Movimientos de inventario",adjust),grid);expand(grid);refresh();}
    private void refresh(){grid.setItems(service.listar());}
    private void form(){Dialog d=new Dialog();d.setHeaderTitle("Ajustar stock");ComboBox<ProductoDTO> product=new ComboBox<>("Producto");product.setItems(productos.listar());product.setItemLabelGenerator(p->p.nombre()+" · actual "+p.stock());IntegerField stock=new IntegerField("Nuevo stock");stock.setMin(0);TextField reason=new TextField("Motivo");d.add(new VerticalLayout(product,stock,reason));Button save=new Button("Guardar",e->{try{if(product.getValue()==null||stock.getValue()==null)throw new IllegalArgumentException("Completá producto y stock");service.ajustar(product.getValue().id(),stock.getValue(),reason.getValue(),UserSession.getUser().id());d.close();refresh();}catch(RuntimeException ex){ViewSupport.error(ex);}});save.addThemeVariants(ButtonVariant.LUMO_PRIMARY);d.getFooter().add(new Button("Cancelar",e->d.close()),save);d.open();}
}
