ALTER TABLE administradores ADD COLUMN IF NOT EXISTS intentos_fallidos INTEGER NOT NULL DEFAULT 0;
ALTER TABLE administradores ADD COLUMN IF NOT EXISTS bloqueado_hasta TIMESTAMP;
ALTER TABLE administradores ADD COLUMN IF NOT EXISTS ultimo_acceso TIMESTAMP;

ALTER TABLE empleados ADD COLUMN IF NOT EXISTS intentos_fallidos INTEGER NOT NULL DEFAULT 0;
ALTER TABLE empleados ADD COLUMN IF NOT EXISTS bloqueado_hasta TIMESTAMP;
ALTER TABLE empleados ADD COLUMN IF NOT EXISTS ultimo_acceso TIMESTAMP;
